name: ci
on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:
  
jobs:
  yaml-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
       node-version: 20

    - name: Imstall yamllint
      run: sudo npm i -g yaml-lint

    - name: Check yaml
      run: /usr/local/lib/node_modules/yaml-lint/dist/cli.js action.yml

  ci-test:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          id: x64
          
    needs: yaml-check
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Test CI
      uses: dabao1955/kernel_build_action@main
      with: 
          kernel-url: https://github.com/LineageOS/android_kernel_google_msm-4.9
          kernel-dir: android_kernel_google_msm-4.9
          branch: lineage-20
          config: b1c1_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 12
          aosp-clang-version: r416183b1
          python-27: true
          disable-lto: true
          overlayfs: true
          lxc: false
          lxc-patch: false
          anykernel3: true
          extra-cmd: CROSS_COMPILE_ARM32=arm-linux-androideabi-  CROSS_COMPILE_ARM32=arm-linux-androideabi- AR=llvm-ar NM=llvm-nm
